builds:
  - id: darwin-amd64
    main: ./
    binary: poptop
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: darwin-arm64
    main: ./
    binary: poptop
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}


release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: poptop
    homepage: "https://github.com/bakks/poptop"
    license: "MIT"
    description: "A modern Top command that dynamically charts system metrics in the terminal."
    tap:
      owner: bakks
      name: homebrew-bakks
    commit_author:
      name: bakks
      email: pbbakkum@gmail.com

checksum:
  name_template: 'checksums.txt'
